/**
 * Nomes do lucide traduzidos pros do Phosphor.
 *
 * Existe porque o banco guarda o nome do ícone como texto (`amenity.icon`), e esses
 * valores foram gravados com os nomes do lucide. Trocar a biblioteca não reescreve o
 * que já está lá, então a tradução acontece na leitura. Enquanto o banco não for
 * migrado, este mapa é o que segura as comodidades exibindo o ícone certo.
 *
 * Falta de entrada aqui é um defeito silencioso: o nome não resolve, a leitura cai no
 * `Sparkle` e a página fica com um brilho genérico no lugar do ícone, sem erro nenhum.
 * Foi o que aconteceu com `Sofa`, `Wifi`, `Droplets` e `PlaneTakeoff`. O guard contra
 * isso é `src/features/listing/AmenityList.logic.test.ts`, que lê o catálogo do SQL
 * versionado e reprova qualquer nome que caia no fallback.
 */
export const LUCIDE_TO_PHOSPHOR: Record<string, string> = {
  AlertCircle: "WarningCircle",
  AlertTriangle: "Warning",
  ArrowDownUp: "ArrowsDownUp",
  BadgeCheck: "SealCheck",
  Banknote: "Money",
  BarChart3: "ChartBar",
  Bike: "Bicycle",
  Bold: "TextB",
  Bot: "Robot",
  Building2: "Buildings",
  BusFront: "Bus",
  CalendarClock: "CalendarDot",
  CalendarDays: "CalendarBlank",
  CalendarRange: "CalendarBlank",
  CheckCircle2: "CheckCircle",
  ChevronDown: "CaretDown",
  ChevronLeft: "CaretLeft",
  ChevronRight: "CaretRight",
  ChevronsUpDown: "CaretUpDown",
  CircleAlert: "WarningCircle",
  CircleCheck: "CheckCircle",
  CircleDollarSign: "CurrencyCircleDollar",
  ConciergeBell: "Bell",
  Container: "Package",
  CornerDownLeft: "ArrowElbowDownLeft",
  Droplets: "Drop",
  Edit2: "PencilSimple",
  ExternalLink: "ArrowSquareOut",
  Filter: "FunnelSimple",
  Grid2x2: "SquaresFour",
  Heading2: "TextHTwo",
  Heading3: "TextHThree",
  HelpCircle: "Question",
  Home: "House",
  ImageIcon: "Image",
  ImageOff: "ImageBroken",
  ImagePlus: "ImageSquare",
  Inbox: "Tray",
  Italic: "TextItalic",
  KeyRound: "Key",
  Landmark: "Bank",
  LayoutDashboard: "SquaresFour",
  LifeBuoy: "Lifebuoy",
  Link2: "Link",
  ListOrdered: "ListNumbers",
  Loader2: "CircleNotch",
  LogIn: "SignIn",
  LogOut: "SignOut",
  Mail: "Envelope",
  Maximize2: "ArrowsOut",
  MessageCircle: "ChatCircle",
  MoreHorizontal: "DotsThree",
  MoreVertical: "DotsThreeVertical",
  PartyPopper: "Confetti",
  PieChart: "ChartPie",
  Plane: "Airplane",
  PlaneTakeoff: "AirplaneTakeoff",
  Quote: "Quotes",
  RefreshCw: "ArrowsClockwise",
  RotateCcw: "ArrowCounterClockwise",
  Save: "FloppyDisk",
  ScanLine: "Scan",
  ScrollText: "Scroll",
  Search: "MagnifyingGlass",
  Send: "PaperPlaneTilt",
  Settings: "Gear",
  Settings2: "Faders",
  Share2: "ShareNetwork",
  ShieldAlert: "ShieldWarning",
  ShieldQuestion: "ShieldChevron",
  Smartphone: "DeviceMobile",
  Sofa: "Couch",
  Sparkles: "Sparkle",
  SquareKanban: "Kanban",
  SquareParking: "CarProfile",
  Store: "Storefront",
  Table2: "Table",
  Trash2: "Trash",
  TrendingUp: "TrendUp",
  TriangleAlert: "Warning",
  Unlink: "LinkBreak",
  User2: "User",
  UserCog: "UserGear",
  Wifi: "WifiHigh",
  Zap: "Lightning",
};
