-- Create 26 Master Guide blog posts for major airports and destinations
-- Onda 1: GRU, VCP, CNF, CWB
-- Onda 2: CGH, BSB, REC, SSA, FOR, POA, CGB, MAO, GYN, BEL, NVT, SDU
-- Onda 3: GIG, JPA, MCZ, THE, POA (salgado-filho), CNG, SPO, JPT, TTE, LIS

INSERT INTO blog_post (id, slug, title, excerpt, body_md, cover_image_url, destination_id, is_published, published_at, created_at, updated_at)
VALUES
  -- Onda 1
  (gen_random_uuid(), 'guia-master-aeroporto-guarulhos', 'Guia Master: Estacionamento em Guarulhos (GRU)', 'Tudo que você precisa saber sobre estacionamento no Aeroporto de Guarulhos. Tarifas, dicas e como reservar online.',
   E'# Guia Master: Estacionamento em Guarulhos (GRU)\n\n## Sobre o Aeroporto\n\nO Aeroporto Internacional de São Paulo/Guarulhos é o maior aeroporto do Brasil e um dos principais hubs da América Latina. Localizado a 25 km de São Paulo, movimenta milhões de passageiros anualmente.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 35-50 | R$ 8-12 | Estacionamento descoberto |\n| Valet | R$ 55-75 | R$ 12-18 | Serviço de manobrista |\n| Coberto | R$ 45-65 | R$ 10-15 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Como reservar estacionamento com antecedência?**\nR: Utilize a plataforma Movepark para reservar seu espaço com até 30 dias de antecedência e garantir melhor preço.\n\n**P: Qual é o tempo limite de espera?**\nR: Você tem 30 minutos de cortesia após a hora de checkout. Após isso, é cobrada a tarifa horária.\n\n**P: Posso estender minha reserva?**\nR: Sim, você pode estender sua reserva diretamente no app ou entrando em contato com o atendimento.\n\n**P: O estacionamento é seguro?**\nR: Todos os estabelecimentos parceiros possuem vigilância 24h, seguros e sistemas de monitoramento.\n\n**P: Há desconto para longa permanência?**\nR: Sim, quanto mais dias você reservar, melhor será o preço por diária.\n\n**P: Posso cancelar minha reserva?**\nR: Você pode cancelar com até 24h de antecedência e receber o reembolso integral.\n\n**P: Qual é a política de atraso no checkout?**\nR: Atrasos são cobrados por hora cheia. Recomendamos fazer checkout antes da hora marcada.\n\n**P: Há estacionamento para veículos grandes?**\nR: Sim, temos vagas especiais para vans, SUVs e veículos grandes.\n\n## Checklist de Viagem\n\n- [ ] Reservar estacionamento com antecedência\n- [ ] Confirmar hora de saída no app\n- [ ] Fotografar o estado do veículo\n- [ ] Guardar a referência do booking\n- [ ] Chegar com antecedência para entrega\n- [ ] Conferir documentação do carro\n- [ ] Revisar recibo de aceitação\n- [ ] Retirar bagagens e itens pessoais\n',
   'https://images.movepark.co/blog/guia-master-guarulhos.jpg', '3a572f42-24ee-4aa8-b209-afada25d14ec', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-viracopos', 'Guia Master: Estacionamento em Viracopos (VCP)', 'Dicas essenciais para estacionar seu carro em Viracopos. Opções de preço, segurança e como reservar.',
   E'# Guia Master: Estacionamento em Viracopos (VCP)\n\n## Sobre o Aeroporto\n\nO Aeroporto de Viracopos é o segundo maior aeroporto de São Paulo, localizado em Campinas. Atende voos domésticos e internacionais com foco em cargas e operações de baixo custo.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 30-45 | R$ 6-10 | Estacionamento descoberto |\n| Valet | R$ 50-70 | R$ 10-15 | Serviço de manobrista |\n| Coberto | R$ 40-60 | R$ 8-12 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Qual é o estacionamento mais próximo do terminal?**\nR: O estacionamento oficial fica a menos de 100 metros do saguão de embarque.\n\n**P: É possível reservar online?**\nR: Sim, na Movepark você reserva seu espaço e paga antecipadamente, economizando tempo.\n\n**P: Qual é a tarifa por horas parciais?**\nR: Cobramos por hora cheia. Até 30 minutos não é cobrado.\n\n**P: O estacionamento tem ar-condicionado?**\nR: Sim, as áreas cobertas têm proteção contra chuva, muito comum em Campinas.\n\n**P: Posso deixar meu carro por 15 dias?**\nR: Sim, não há limite de dias. As tarifas de longa permanência são mais acessíveis.\n\n**P: Há ônibus de transporte até o terminal?**\nR: Sim, você tem acesso a ônibus de transporte gratuito a cada 10 minutos.\n\n**P: Qual é a política de danos ao veículo?**\nR: O estacionamento é responsável por furtos e danos durante a permanência.\n\n**P: Posso estacionar uma motocicleta?**\nR: Sim, há área específica para motos com tarifa diferenciada.\n\n## Checklist de Viagem\n\n- [ ] Chegar 15 minutos antes do horário marcado\n- [ ] Levar documento de identidade e CNH\n- [ ] Fotografar estado geral do veículo\n- [ ] Anotar dados do seu carro na entrada\n- [ ] Guardar recibo e referência do booking\n- [ ] Proteger valores pessoais dentro do carro\n- [ ] Conferir nível de combustível antes de deixar\n- [ ] Deixar contato de emergência registrado\n',
   'https://images.movepark.co/blog/guia-master-viracopos.jpg', 'da58673f-5dfd-4130-999b-5c987f353330', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-confins', 'Guia Master: Estacionamento em Confins (CNF)', 'Estacionamento em Belo Horizonte: tarifas, facilidades e dicas para reservar seu espaço em Confins.',
   E'# Guia Master: Estacionamento em Confins (CNF)\n\n## Sobre o Aeroporto\n\nO Aeroporto de Confins atende a região metropolitana de Belo Horizonte. É o principal hub da região nordeste de Minas Gerais.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 32-48 | R$ 7-11 | Estacionamento descoberto |\n| Valet | R$ 52-72 | R$ 11-16 | Serviço de manobrista |\n| Coberto | R$ 42-62 | R$ 9-13 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Qual é a distância do estacionamento ao terminal?**\nR: Fica a apenas 5 minutos de caminhada do saguão principal.\n\n**P: Há estacionamento para deficientes?**\nR: Sim, com vagas reservadas próximas à entrada e sem cobrança de taxa adicional.\n\n**P: Como funciona a reserva antecipada?**\nR: Através da Movepark, você escolhe as datas, paga online e recebe um código de acesso.\n\n**P: O estacionamento tem cobertura?**\nR: Sim, temos áreas cobertas para proteção contra chuva e sol.\n\n**P: Posso reservar por quantos dias quiser?**\nR: Sim, sem limite de dias. Quanto mais tempo, melhor o preço por diária.\n\n**P: Qual é o horário de funcionamento?**\nR: 24 horas por dia, 7 dias por semana.\n\n**P: Há serviço de limpeza do carro?**\nR: Não incluído na tarifa, mas oferecemos como serviço adicional.\n\n**P: Posso sair e voltar com a mesma reserva?**\nR: Não, cada entrada/saída é considerada uma nova permanência.\n\n## Checklist de Viagem\n\n- [ ] Reservar com antecedência pela Movepark\n- [ ] Ter documento de identidade e carteira de motorista\n- [ ] Chegar 20 minutos antes do horário acordado\n- [ ] Inspecionar o veículo com cuidado\n- [ ] Tirar fotos do estado atual do carro\n- [ ] Guardar chaves em local seguro\n- [ ] Anotar número de série do reserva\n- [ ] Revisar termos e condições\n',
   'https://images.movepark.co/blog/guia-master-confins.jpg', 'f6e92fc2-b253-405f-9a25-b3fea2491295', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-curitiba', 'Guia Master: Estacionamento em Curitiba (CWB)', 'Tudo sobre estacionamento no Aeroporto Afonso Pena em Curitiba. Preços, reservas e facilidades.',
   E'# Guia Master: Estacionamento em Curitiba (CWB)\n\n## Sobre o Aeroporto\n\nO Aeroporto Afonso Pena é o principal aeroporto do Paraná, atendendo a capital Curitiba e a região sul.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 28-42 | R$ 6-9 | Estacionamento descoberto |\n| Valet | R$ 48-68 | R$ 10-14 | Serviço de manobrista |\n| Coberto | R$ 38-58 | R$ 8-11 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Como chego ao terminal a pé do estacionamento?**\nR: É uma caminhada de menos de 10 minutos até a entrada principal.\n\n**P: Posso reservar estacionamento para alguém que vai buscar meu carro?**\nR: Sim, informando os dados dessa pessoa no momento da reserva.\n\n**P: Há desconto para clientes frequentes?**\nR: Sim, oferecemos programas de fidelidade com descontos progressivos.\n\n**P: O estacionamento aceita todos os tipos de veículo?**\nR: Sim, inclusive SUVs grandes e vans, com tarifas diferenciadas.\n\n**P: Posso cancelar minha reserva a qualquer momento?**\nR: Cancelamentos com até 48h recebem reembolso integral.\n\n**P: Há seguro contra roubo incluído?**\nR: Sim, está incluído na tarifa e cobre furto e danos.\n\n**P: O que devo fazer em caso de dano ao veículo?**\nR: Comunique imediatamente à equipe e fotografe o dano para registro.\n\n**P: Há transporte entre o estacionamento e o terminal?**\nR: Sim, temos ônibus de transporte a cada 15 minutos.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva com pelo menos 3 dias de antecedência\n- [ ] Verificar documentação do veículo\n- [ ] Limpar o interior do carro\n- [ ] Conferir fechamento de portas e janelas\n- [ ] Documentar estado do carro com fotos\n- [ ] Guardar voucher de confirmação\n- [ ] Acompanhar entrega até a vaga\n- [ ] Revisar contrato de estacionamento\n',
   'https://images.movepark.co/blog/guia-master-curitiba.jpg', 'c07e27e1-09d7-4499-afeb-fa84671ced3c', true, now(), now(), now()),

  -- Onda 2
  (gen_random_uuid(), 'guia-master-aeroporto-congonhas', 'Guia Master: Estacionamento em Congonhas (CGH)', 'Estacionamento próximo ao Aeroporto de Congonhas em São Paulo. Reservas online, tarifas e facilidades.',
   E'# Guia Master: Estacionamento em Congonhas (CGH)\n\n## Sobre o Aeroporto\n\nO Aeroporto de Congonhas é o aeroporto mais movimentado do Brasil em número de voos domésticos, localizado no coração de São Paulo.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 45-60 | R$ 10-14 | Estacionamento descoberto |\n| Valet | R$ 65-85 | R$ 14-20 | Serviço de manobrista |\n| Coberto | R$ 55-75 | R$ 12-17 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Qual é a tarifa mais barata para estacionamento em Congonhas?**\nR: O self-park descoberto é a opção mais econômica, com diárias a partir de R$ 45.\n\n**P: Como funciona a entrada e saída rápida?**\nR: Você pré-registra dados do carro online e recebe um QR code para acesso automático.\n\n**P: Há estacionamento de curta duração?**\nR: Sim, oferecemos tarifas especiais para deixar apenas bagagem ou esperar.\n\n**P: Posso renovar minha reserva se precisar ficar mais tempo?**\nR: Sim, você pode estender a reserva pelo app ou telefone.\n\n**P: Qual é a melhor hora para chegar ao estacionamento?**\nR: Madrugada é menos congestionada. Evite horários de pico (7-9am, 5-8pm).\n\n**P: O estacionamento tem câmeras de vigilância?**\nR: Sim, monitoramento 24h com gravação contínua de todas as áreas.\n\n**P: Posso deixar meu carro por 45 dias?**\nR: Sim, com tarifas especiais para estadias longas. Consulte valores.\n\n**P: Há vagas acessíveis para PcD?**\nR: Sim, com gratuidade da taxa de serviço ao apresentar cartão de PcD.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva online na Movepark\n- [ ] Baixar comprovante de reserva no celular\n- [ ] Abastecer antes de deixar o carro\n- [ ] Conferir documentação e GPS\n- [ ] Fotografar o estado geral\n- [ ] Guardar cartão de acesso\n- [ ] Fazer inspeção visual com funcionário\n- [ ] Solicitar recibo detalhado\n',
   'https://images.movepark.co/blog/guia-master-congonhas.jpg', 'ede0de4e-bdc9-4c36-96c8-a7a9e72a4edc', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-brasilia', 'Guia Master: Estacionamento em Brasília (BSB)', 'Estacionamento no Aeroporto Internacional de Brasília. Tarifas, reservas e serviços disponíveis.',
   E'# Guia Master: Estacionamento em Brasília (BSB)\n\n## Sobre o Aeroporto\n\nO Aeroporto de Brasília é o hub central do Brasil, conectando regiões norte, nordeste e centro-oeste.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 30-45 | R$ 7-10 | Estacionamento descoberto |\n| Valet | R$ 50-70 | R$ 10-15 | Serviço de manobrista |\n| Coberto | R$ 40-60 | R$ 9-12 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Qual é a melhor opção de estacionamento em Brasília?**\nR: Self-park é mais econômico; valet oferece comodidade; coberto é o meio termo.\n\n**P: Posso reservar com quantos dias de antecedência?**\nR: Até 60 dias antes da data de entrada.\n\n**P: Há seguro incluído?**\nR: Sim, cobertura contra roubo, furto e danos causados pelo próprio estacionamento.\n\n**P: O aeroporto fica longe da cidade?**\nR: Fica a 15 km do centro, cerca de 20 minutos de carro.\n\n**P: Qual tipo de carro é aceito?**\nR: Todos, inclusive motos, bicicletas e carros elétricos.\n\n**P: Há carregador para carros elétricos?**\nR: Sim, temos pontos de recarga disponíveis.\n\n**P: Posso pagar na entrada ou precisa ser online?**\nR: Recomendamos reservar online para garantir vaga e pagar antecipadamente.\n\n**P: O estacionamento fica aberto à noite?**\nR: Sim, 24 horas por dia com vigilância permanente.\n\n## Checklist de Viagem\n\n- [ ] Reservar estacionamento com 7 dias de antecedência\n- [ ] Confirmar horário de chegada\n- [ ] Levar documentação do veículo\n- [ ] Deixar combustível no mínimo necessário\n- [ ] Fotografar placa e estado do carro\n- [ ] Guardar referência da reserva\n- [ ] Informar contato de emergência\n- [ ] Anotar dados do atendente\n',
   'https://images.movepark.co/blog/guia-master-brasilia.jpg', '0310460e-a00f-4895-8e4c-a23f06e639e3', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-recife', 'Guia Master: Estacionamento em Recife (REC)', 'Guia completo de estacionamento no Aeroporto de Guararapes em Recife. Opções, tarifas e dicas.',
   E'# Guia Master: Estacionamento em Recife (REC)\n\n## Sobre o Aeroporto\n\nO Aeroporto Internacional do Recife/Guararapes é o principal hub do nordeste, com voos para todo o Brasil e exterior.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 32-48 | R$ 7-11 | Estacionamento descoberto |\n| Valet | R$ 52-72 | R$ 11-16 | Serviço de manobrista |\n| Coberto | R$ 42-62 | R$ 9-13 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: O clima quente afeta o carro?**\nR: Recomendamos estacionamento coberto para maior proteção contra o sol intenso.\n\n**P: Há desconto para turistas?**\nR: Sim, oferecemos descontos especiais para viajantes na primeira reserva.\n\n**P: Como é a segurança do estacionamento?**\nR: Vigilância 24h, câmeras em todas as áreas e seguro incluído.\n\n**P: Posso deixar documentos pessoais no carro?**\nR: Não recomendamos deixar valores ou documentos no interior.\n\n**P: Qual é a política de atraso?**\nR: Até 30 minutos sem cobrança. Após isso, cobra-se a hora inteira.\n\n**P: Há ônibus de transporte?**\nR: Sim, transporte gratuito a cada 20 minutos.\n\n**P: Posso fazer reserva por telefone?**\nR: Sim, mas é mais rápido e seguro reservar online na Movepark.\n\n**P: Qual é o horário de pico no estacionamento?**\nR: 6-9am pela manhã e 4-7pm no final da tarde.\n\n## Checklist de Viagem\n\n- [ ] Reservar com antecedência\n- [ ] Baixar aplicativo da Movepark\n- [ ] Confirmar dados do veículo\n- [ ] Chegar 15 minutos antes\n- [ ] Fazer inspeção com funcionário\n- [ ] Documentar fotos do carro\n- [ ] Guardar voucher\n- [ ] Deixar contato atualizado\n',
   'https://images.movepark.co/blog/guia-master-recife.jpg', 'ee60459f-0a19-4177-8d3b-c121c899939f', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-salvador', 'Guia Master: Estacionamento em Salvador (SSA)', 'Tudo sobre estacionamento no Aeroporto de Salvador. Reservas, tarifas e facilidades disponíveis.',
   E'# Guia Master: Estacionamento em Salvador (SSA)\n\n## Sobre o Aeroporto\n\nO Aeroporto Internacional de Salvador é o gateway para a Bahia, com voos diretos para várias capitais.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 30-45 | R$ 7-10 | Estacionamento descoberto |\n| Valet | R$ 50-70 | R$ 10-15 | Serviço de manobrista |\n| Coberto | R$ 40-60 | R$ 9-12 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Como funciona a entrada ao estacionamento?**\nR: Apresente seu voucher digital e receba as chaves de acesso.\n\n**P: Há limite de permanência?**\nR: Não, você pode deixar por quantos dias precisar.\n\n**P: Como recebo meu carro de volta?**\nR: Você avisa a hora de saída e o carro é trazido até você em 10 minutos.\n\n**P: Posso alterar a data de saída?**\nR: Sim, você pode estender sua permanência a qualquer momento.\n\n**P: O estacionamento fica perto do terminal?**\nR: Sim, a apenas 5 minutos do saguão de embarque.\n\n**P: Há cobrança por antecipação de saída?**\nR: Não, você só paga pelo tempo de permanência real.\n\n**P: Qual é a forma de pagamento?**\nR: Cartão de crédito, débito ou dinheiro na saída se reservar na hora.\n\n**P: Há atendimento 24 horas?**\nR: Sim, equipe disponível a qualquer horário.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva na Movepark\n- [ ] Confirmar horário de chegada\n- [ ] Inspecionar o veículo\n- [ ] Tirar fotos de referência\n- [ ] Guardar voucher\n- [ ] Anotar número da vaga\n- [ ] Deixar contato de emergência\n- [ ] Revisar contrato\n',
   'https://images.movepark.co/blog/guia-master-salvador.jpg', '44e97a3e-1a25-4bf9-b24b-e8c5912570ad', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-fortaleza', 'Guia Master: Estacionamento em Fortaleza (FOR)', 'Guia de estacionamento no Aeroporto de Fortaleza. Opções de preço, reservas online e dicas.',
   E'# Guia Master: Estacionamento em Fortaleza (FOR)\n\n## Sobre o Aeroporto\n\nO Aeroporto Internacional de Fortaleza é um importante hub do nordeste, conhecido pela hospitalidade e clima agradável.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 28-42 | R$ 6-9 | Estacionamento descoberto |\n| Valet | R$ 48-68 | R$ 10-14 | Serviço de manobrista |\n| Coberto | R$ 38-58 | R$ 8-11 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: O clima afeta a segurança do carro?**\nR: Não, temos cobertura contra intempéries e vigilância constante.\n\n**P: Qual é a proximidade com o terminal?**\nR: Menos de 500 metros de caminhada até a entrada principal.\n\n**P: Hay estacionamento para carros de luxo?**\nR: Sim, com seguro especial para veículos de alto valor.\n\n**P: Posso deixar meu carro por um mês?**\nR: Sim, com tarifa especial de longa permanência.\n\n**P: Como faço para cancelar minha reserva?**\nR: Cancele online até 48h antes para reembolso integral.\n\n**P: Há valet que lava o carro?**\nR: Sim, oferecemos serviço adicional de limpeza e enceramento.\n\n**P: Qual é a política de entrada madrugada?**\nR: A mesma tarifa, sem aumentos noturnos.\n\n**P: Posso pagar com dinheiro?**\nR: Preferimos cartão, mas aceitamos dinheiro na chegada.\n\n## Checklist de Viagem\n\n- [ ] Reservar com 3 dias de antecedência\n- [ ] Confirmar dados pessoais\n- [ ] Levar documentação\n- [ ] Chegar no horário marcado\n- [ ] Fazer checklist do carro\n- [ ] Guardar recibo\n- [ ] Deixar contato principal\n- [ ] Indicar próxima viagem\n',
   'https://images.movepark.co/blog/guia-master-fortaleza.jpg', '7f603b7e-ffbb-44ea-ad23-d4a9ec279b14', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-porto-alegre', 'Guia Master: Estacionamento em Porto Alegre (POA)', 'Estacionamento no Aeroporto Salgado Filho em Porto Alegre. Tarifas, reservas e facilidades.',
   E'# Guia Master: Estacionamento em Porto Alegre (POA)\n\n## Sobre o Aeroporto\n\nO Aeroporto Salgado Filho é o principal aeroporto do Rio Grande do Sul, gateway para a região sul.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 32-48 | R$ 7-11 | Estacionamento descoberto |\n| Valet | R$ 52-72 | R$ 11-16 | Serviço de manobrista |\n| Coberto | R$ 42-62 | R$ 9-13 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Como reservo estacionamento em Porto Alegre?**\nR: Pela Movepark, escolhendo as datas e tipo de estacionamento desejado.\n\n**P: Há desconto para estacionamento mensal?**\nR: Sim, quanto maior o período, menor o valor diário.\n\n**P: O inverno afeta o estacionamento?**\nR: Recomendamos coberto no inverno para melhor proteção.\n\n**P: Qual é a distância ao terminal?**\nR: Aproximadamente 2 km, com transporte gratuito.\n\n**P: Posso deixar documentos valiosos no carro?**\nR: Não recomendamos; leve consigo ou use o cofre do hotel.\n\n**P: Há garantia de devolução na hora?**\nR: Sim, se avisado com 2 horas de antecedência.\n\n**P: Qual é a melhor opção preço/benefício?**\nR: Self-park é mais barato; valet oferece praticidade.\n\n**P: Posso modificar dados da reserva?**\nR: Sim, até 48h antes com cancelamento ou ajuste de datas.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva na Movepark\n- [ ] Confirmar o horário\n- [ ] Verificar combustível\n- [ ] Inspecionar exterior\n- [ ] Fotografar documentação\n- [ ] Guardar chave na vaga\n- [ ] Anotar contato local\n- [ ] Revisar seguro\n',
   'https://images.movepark.co/blog/guia-master-porto-alegre.jpg', '1e8b522c-31b1-4165-ad71-59bb86706325', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-cuiaba', 'Guia Master: Estacionamento em Cuiabá (CGB)', 'Tudo sobre estacionamento no Aeroporto de Cuiabá. Opções de preço, reservas e segurança.',
   E'# Guia Master: Estacionamento em Cuiabá (CGB)\n\n## Sobre o Aeroporto\n\nO Aeroporto de Cuiabá é o gateway para o Mato Grosso e para o Pantanal, um dos destinos naturais mais importantes do Brasil.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 28-42 | R$ 6-9 | Estacionamento descoberto |\n| Valet | R$ 48-68 | R$ 10-14 | Serviço de manobrista |\n| Coberto | R$ 38-58 | R$ 8-11 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Qual é o estacionamento mais barato?**\nR: Self-park descoberto, a partir de R$ 28 por dia.\n\n**P: O calor afeta os carros?**\nR: Sim, recomendamos opção coberta para melhor proteção.\n\n**P: Há limite de dias?**\nR: Não, você pode deixar por quanto tempo quiser.\n\n**P: Como funciona a devolução do carro?**\nR: Você confirma a saída e recebe o carro em até 15 minutos.\n\n**P: O estacionamento tem seguro?**\nR: Sim, cobertura completa contra roubo e danos.\n\n**P: Qual é a melhor hora para chegar?**\nR: Evite picos de 7-9am e 5-7pm.\n\n**P: Posso estacionar motos e bicicletas?**\nR: Sim, com tarifas especiais reduzidas.\n\n**P: Há atendimento em português?**\nR: Sim, atendimento fluente em português.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva online\n- [ ] Confirmar data de entrada\n- [ ] Levar carteira de motorista\n- [ ] Documentar estado do carro\n- [ ] Guardar recibo de entrada\n- [ ] Deixar número de contato\n- [ ] Indicar hora aproximada de saída\n- [ ] Anotar localização da vaga\n',
   'https://images.movepark.co/blog/guia-master-cuiaba.jpg', '4acc0236-64bb-4dcd-a6a5-dd110bdf9749', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-manaus', 'Guia Master: Estacionamento em Manaus (MAO)', 'Estacionamento no Aeroporto de Manaus. Tarifas, reservas e informações úteis para viajantes.',
   E'# Guia Master: Estacionamento em Manaus (MAO)\n\n## Sobre a Região\n\nManaus é a porta de entrada para a Amazônia e um importante centro comercial do Brasil. O Aeroporto Internacional de Manaus conecta a região ao resto do país.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 30-45 | R$ 7-10 | Estacionamento descoberto |\n| Valet | R$ 50-70 | R$ 10-15 | Serviço de manobrista |\n| Coberto | R$ 40-60 | R$ 9-12 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Como faço para reservar estacionamento em Manaus?**\nR: Através da Movepark, selecionando as datas de entrada e saída.\n\n**P: O clima quente e úmido afeta o carro?**\nR: Recomendamos coberto para proteção contra umidade e chuva.\n\n**P: Há desconto para turistas?**\nR: Sim, oferecemos pacotes especiais para viajantes.\n\n**P: Qual é a distância do aeroporto ao centro de Manaus?**\nR: Aproximadamente 14 km, cerca de 20 minutos de carro.\n\n**P: O estacionamento fica aberto à noite?**\nR: Sim, 24 horas com vigilância permanente.\n\n**P: Posso deixar o carro por 2 semanas?**\nR: Sim, com tarifa especial de longa permanência.\n\n**P: Como é a segurança?**\nR: Vigilância 24h com câmeras em todas as áreas e seguro incluído.\n\n**P: Há transporte entre estacionamento e terminal?**\nR: Sim, ônibus gratuito a cada 20 minutos.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva antecipada\n- [ ] Confirmar dados\n- [ ] Chegar com antecedência\n- [ ] Inspeccionar o veículo\n- [ ] Fotografar placa e estado\n- [ ] Guardar voucher\n- [ ] Deixar contato local\n- [ ] Revisar documentação\n',
   'https://images.movepark.co/blog/guia-master-manaus.jpg', NULL, true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-goiania', 'Guia Master: Estacionamento em Goiânia (GYN)', 'Guia completo de estacionamento no Aeroporto de Goiânia. Tarifas, reservas e facilidades.',
   E'# Guia Master: Estacionamento em Goiânia (GYN)\n\n## Sobre o Aeroporto\n\nO Aeroporto Internacional de Goiânia é o principal hub do estado de Goiás, conectando a região centro-oeste.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 28-42 | R$ 6-9 | Estacionamento descoberto |\n| Valet | R$ 48-68 | R$ 10-14 | Serviço de manobrista |\n| Coberto | R$ 38-58 | R$ 8-11 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Qual é a opção mais barata?**\nR: Self-park descoberto oferece as melhores tarifas.\n\n**P: Como funciona a reserva?**\nR: Acesse a Movepark, escolha as datas e conclua o pagamento online.\n\n**P: Posso cancelar minha reserva?**\nR: Sim, com até 48h de antecedência para reembolso integral.\n\n**P: O estacionamento fica próximo ao terminal?**\nR: Sim, menos de 1 km de distância.\n\n**P: Há seguro incluído?**\nR: Sim, cobertura contra roubo e danos causados pelo estacionamento.\n\n**P: Qual é a melhor época para visitar Goiânia?**\nR: Qualquer época; o clima é subtropical o ano todo.\n\n**P: Posso deixar o carro por 30 dias?**\nR: Sim, com tarifas especiais para estadias longas.\n\n**P: Há atendimento em inglês?**\nR: Nosso atendimento principal é em português.\n\n## Checklist de Viagem\n\n- [ ] Reservar na Movepark\n- [ ] Confirmar data de partida\n- [ ] Verificar documentação\n- [ ] Chegar cedo\n- [ ] Fazer inspeção detalhada\n- [ ] Tirar fotos de referência\n- [ ] Guardar recibo\n- [ ] Deixar telefone de contato\n',
   'https://images.movepark.co/blog/guia-master-goiania.jpg', '5a40fc3f-ef05-4270-a3d3-ebca2fbbb4ee', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-belem', 'Guia Master: Estacionamento em Belém (BEL)', 'Estacionamento em Belém. Tarifas, reservas online e informações para viajantes na Amazônia.',
   E'# Guia Master: Estacionamento em Belém (BEL)\n\n## Sobre a Região\n\nBelém é a porta de entrada para a Amazônia oriental e um importante centro econômico do Brasil. O Aeroporto de Belém conecta a região ao resto do país.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 26-40 | R$ 6-8 | Estacionamento descoberto |\n| Valet | R$ 46-66 | R$ 9-13 | Serviço de manobrista |\n| Coberto | R$ 36-56 | R$ 8-10 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Como faço para reservar?**\nR: Acesse a Movepark, selecione as datas e pague online de forma segura.\n\n**P: Qual é a melhor opção para o clima tropical?**\nR: Coberto, para proteção contra chuva e umidade intensa.\n\n**P: Há desconto para turistas?**\nR: Sim, oferecemos promoções especiais para viajantes.\n\n**P: Qual é a distância do aeroporto ao centro?**\nR: Aproximadamente 3 km, cerca de 10 minutos de carro.\n\n**P: O estacionamento aceita todos os veículos?**\nR: Sim, carros, motos, vans e veículos grandes.\n\n**P: Há vigilância 24 horas?**\nR: Sim, monitoramento constante com câmeras em todas as áreas.\n\n**P: Posso deixar por 15 dias?**\nR: Sim, com tarifas especiais para longa permanência.\n\n**P: Como é o atendimento?**\nR: Equipe cordial e atenciosa disponível 24 horas.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva com antecedência\n- [ ] Confirmar dados pessoais\n- [ ] Levar carteira de motorista\n- [ ] Inspecionar o veículo\n- [ ] Documentar estado\n- [ ] Guardar voucher\n- [ ] Deixar contato\n- [ ] Anotar instruções\n',
   'https://images.movepark.co/blog/guia-master-belem.jpg', NULL, true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-navegantes', 'Guia Master: Estacionamento em Navegantes (NVT)', 'Estacionamento no Aeroporto de Navegantes em Santa Catarina. Tarifas, reservas e facilidades.',
   E'# Guia Master: Estacionamento em Navegantes (NVT)\n\n## Sobre o Aeroporto\n\nO Aeroporto Internacional de Navegantes serve a região do litoral catarinense, importante destino turístico e de negócios.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 30-45 | R$ 7-10 | Estacionamento descoberto |\n| Valet | R$ 50-70 | R$ 10-15 | Serviço de manobrista |\n| Coberto | R$ 40-60 | R$ 9-12 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Qual é a forma mais barata de estacionar?**\nR: Self-park descoberto, a partir de R$ 30 por dia.\n\n**P: O estacionamento fica próximo à praia?**\nR: Sim, Navegantes fica na costa; ideal para turismo.\n\n**P: Há estacionamento para RVs e trailers?**\nR: Sim, com vagas especiais e tarifas diferenciadas.\n\n**P: Como funciona a reserva?**\nR: Na Movepark, escolha datas e tipo de estacionamento.\n\n**P: Posso cancelar sem perda?**\nR: Sim, até 24h antes para reembolso integral.\n\n**P: Qual é a segurança do local?**\nR: Vigilância 24h, câmeras, seguro incluído.\n\n**P: O aeroporto fica longe da cidade?**\nR: Apenas 10 km do centro de Navegantes.\n\n**P: Há transporte entre estacionamento e terminal?**\nR: Sim, transporte gratuito a cada 15 minutos.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva online\n- [ ] Confirmar horário\n- [ ] Levar documentos\n- [ ] Inspecionar carro\n- [ ] Fotografar placa\n- [ ] Guardar recibo\n- [ ] Deixar contato\n- [ ] Anotar vaga\n',
   'https://images.movepark.co/blog/guia-master-navegantes.jpg', '9ce0ae4c-a6f9-4b90-80f8-aadf0bb95012', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-santos-dumont', 'Guia Master: Estacionamento em Santos Dumont (SDU)', 'Guia de estacionamento no Aeroporto Santos Dumont no Rio de Janeiro. Tarifas e reservas.',
   E'# Guia Master: Estacionamento em Santos Dumont (SDU)\n\n## Sobre o Aeroporto\n\nO Aeroporto Santos Dumont é o aeroporto mais central do Rio de Janeiro, estrategicamente localizado para voos domésticos rápidos.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 35-50 | R$ 8-12 | Estacionamento descoberto |\n| Valet | R$ 55-75 | R$ 12-18 | Serviço de manobrista |\n| Coberto | R$ 45-65 | R$ 10-15 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Como reservo estacionamento em Santos Dumont?**\nR: Pela Movepark, selecionando tipo e datas de permanência.\n\n**P: Qual é a proximidade com o centro do Rio?**\nR: Fica no coração do centro, a poucos minutos de tudo.\n\n**P: Há estacionamento para curta duração?**\nR: Sim, oferecemos tarifas especiais para deixar apenas bagagem.\n\n**P: O estacionamento é seguro?**\nR: Sim, vigilância 24h com cobertura de seguro.\n\n**P: Posso deixar o carro por 1 mês?**\nR: Sim, com tarifa especial de longa permanência.\n\n**P: Qual é a melhor forma de pagar?**\nR: Cartão de crédito para segurança e praticidade.\n\n**P: Há ônibus de transporte?**\nR: Sim, transporte gratuito a cada 10 minutos.\n\n**P: Posso reservar com quanto antecedência?**\nR: Até 90 dias antes da data desejada.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva com antecedência\n- [ ] Confirmar documentação\n- [ ] Chegar 15 minutos antes\n- [ ] Inspecionar o veículo\n- [ ] Fotografar estado\n- [ ] Guardar voucher\n- [ ] Deixar contato\n- [ ] Revisar contrato\n',
   'https://images.movepark.co/blog/guia-master-santos-dumont.jpg', '3b386587-5fa0-45a1-b2b5-c7ebc71ea1c6', true, now(), now(), now()),

  -- Onda 3
  (gen_random_uuid(), 'guia-master-aeroporto-galeao', 'Guia Master: Estacionamento no Galeão (GIG)', 'Tudo sobre estacionamento no Aeroporto do Galeão no Rio. Opções, tarifas e facilidades.',
   E'# Guia Master: Estacionamento no Galeão (GIG)\n\n## Sobre o Aeroporto\n\nO Aeroporto do Galeão é o maior aeroporto do Rio de Janeiro e um dos principais hubs internacionais do Brasil.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 40-55 | R$ 9-13 | Estacionamento descoberto |\n| Valet | R$ 60-80 | R$ 13-19 | Serviço de manobrista |\n| Coberto | R$ 50-70 | R$ 11-16 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Como chego do Galeão ao centro do Rio?**\nR: Aproximadamente 20 km, cerca de 30 minutos de carro dependendo do trânsito.\n\n**P: Posso fazer reserva online?**\nR: Sim, recomendamos reservar na Movepark para garantir melhor preço.\n\n**P: Qual é a tarifa mais barata?**\nR: Self-park descoberto a partir de R$ 40 por dia.\n\n**P: Há seguro incluído?**\nR: Sim, cobertura completa contra roubo e danos.\n\n**P: O estacionamento fica próximo ao saguão?**\nR: A alguns minutos de caminhada com sinalização clara.\n\n**P: Posso deixar o carro por 2 semanas?**\nR: Sim, com tarifa especial de longa permanência.\n\n**P: Há transporte entre estacionamento e terminal?**\nR: Sim, transporte gratuito disponível 24h.\n\n**P: Qual é a melhor opção no verão?**\nR: Coberto, para proteção contra o calor intenso.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva antecipada\n- [ ] Confirmar dados pessoais\n- [ ] Chegar com tempo\n- [ ] Inspecionar o veículo\n- [ ] Documentar fotos\n- [ ] Guardar recibo\n- [ ] Deixar contato\n- [ ] Revisar termos\n',
   'https://images.movepark.co/blog/guia-master-galeao.jpg', 'cdf91ad4-91b5-425d-9709-131e7421d2b2', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-joao-pessoa', 'Guia Master: Estacionamento em João Pessoa (JPA)', 'Estacionamento no Aeroporto de João Pessoa. Tarifas, reservas e informações úteis.',
   E'# Guia Master: Estacionamento em João Pessoa (JPA)\n\n## Sobre o Aeroporto\n\nO Aeroporto de João Pessoa é o principal hub da Paraíba, conectando a região nordeste ao resto do país.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 28-42 | R$ 6-9 | Estacionamento descoberto |\n| Valet | R$ 48-68 | R$ 10-14 | Serviço de manobrista |\n| Coberto | R$ 38-58 | R$ 8-11 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Como funciona a reserva?**\nR: Acesse a Movepark, selecione as datas e finalize o pagamento online.\n\n**P: Qual é a opção mais barata?**\nR: Self-park descoberto oferece as melhores tarifas.\n\n**P: O aeroporto fica longe do centro?**\nR: Aproximadamente 8 km, cerca de 15 minutos de carro.\n\n**P: Há desconto para turistas?**\nR: Sim, oferecemos promoções especiais para visitantes.\n\n**P: Posso cancelar minha reserva?**\nR: Sim, com até 48h antes para reembolso integral.\n\n**P: O estacionamento tem vigilância?**\nR: Sim, 24 horas com câmeras em todas as áreas.\n\n**P: Há limit de permanência?**\nR: Não, você pode deixar por quanto tempo precisar.\n\n**P: Qual é o atendimento?**\nR: Equipe disponível 24h para suporte.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva na Movepark\n- [ ] Confirmar hora de chegada\n- [ ] Levar carteira de motorista\n- [ ] Inspeccionar veículo\n- [ ] Tirar fotos\n- [ ] Guardar voucher\n- [ ] Deixar telefone\n- [ ] Anotar instruções\n',
   'https://images.movepark.co/blog/guia-master-joao-pessoa.jpg', 'ae5adf40-5516-46d4-a177-4a78ed76c639', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-maceio', 'Guia Master: Estacionamento em Maceió (MCZ)', 'Guia completo de estacionamento no Aeroporto de Maceió. Tarifas, reservas e facilidades.',
   E'# Guia Master: Estacionamento em Maceió (MCZ)\n\n## Sobre o Aeroporto\n\nO Aeroporto de Maceió é o principal aeroporto de Alagoas, porta de entrada para as praias nordestinas.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 26-40 | R$ 6-8 | Estacionamento descoberto |\n| Valet | R$ 46-66 | R$ 9-13 | Serviço de manobrista |\n| Coberto | R$ 36-56 | R$ 8-10 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Qual é a tarifa mais barata?**\nR: Self-park descoberto a partir de R$ 26 por dia.\n\n**P: Como reservo?**\nR: Na Movepark, escolhendo tipo e datas de permanência.\n\n**P: O aeroporto fica perto das praias?**\nR: Sim, muito próximo; ideal para turismo de praia.\n\n**P: Há desconto para longa permanência?**\nR: Sim, quanto mais dias, melhor o preço.\n\n**P: Posso cancelar sem multa?**\nR: Sim, até 24h antes para reembolso completo.\n\n**P: O estacionamento é seguro?**\nR: Sim, vigilância 24h e seguro incluído.\n\n**P: Qual é a melhor opção no verão?**\nR: Coberto, para melhor proteção contra o calor.\n\n**P: Há transporte para o terminal?**\nR: Sim, transporte gratuito disponível.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva online\n- [ ] Confirmar dados\n- [ ] Chegar cedo\n- [ ] Inspeccionar carro\n- [ ] Documentar fotos\n- [ ] Guardar recibo\n- [ ] Deixar contato\n- [ ] Anotar vaga\n',
   'https://images.movepark.co/blog/guia-master-maceio.jpg', '2941dce6-df09-4903-a3da-a500f26b9f07', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-teresina', 'Guia Master: Estacionamento em Teresina (THE)', 'Estacionamento no Aeroporto de Teresina no Piauí. Tarifas, reservas e informações.',
   E'# Guia Master: Estacionamento em Teresina (THE)\n\n## Sobre o Aeroporto\n\nO Aeroporto de Teresina é o principal aeroporto do Piauí, conectando a região norte-nordeste ao resto do país.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 24-38 | R$ 5-7 | Estacionamento descoberto |\n| Valet | R$ 44-64 | R$ 8-12 | Serviço de manobrista |\n| Coberto | R$ 34-54 | R$ 7-9 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Como funciona a reserva?**\nR: Acesse a Movepark, selecione datas e finalize a compra online.\n\n**P: Qual é a tarifa mais acessível?**\nR: Self-park descoberto a partir de R$ 24 por dia.\n\n**P: O aeroporto fica longe do centro?**\nR: Aproximadamente 5 km, cerca de 10 minutos de carro.\n\n**P: Há desconto para turistas?**\nR: Sim, oferecemos promoções especiais.\n\n**P: Posso cancelar minha reserva?**\nR: Sim, com até 48h de antecedência.\n\n**P: O estacionamento tem seguro?**\nR: Sim, cobertura completa incluída.\n\n**P: Há limite de dias?**\nR: Não, você pode deixar por quanto tempo quiser.\n\n**P: Qual é o atendimento?**\nR: Equipe 24h disponível.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva antecipada\n- [ ] Confirmar dados pessoais\n- [ ] Levar documentos\n- [ ] Inspecionar veículo\n- [ ] Fotografar estado\n- [ ] Guardar recibo\n- [ ] Deixar telefone\n- [ ] Revisar contrato\n',
   'https://images.movepark.co/blog/guia-master-teresina.jpg', 'e76dca39-a83f-44b7-af62-0d9c9be864c0', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-salgado-filho', 'Guia Master: Estacionamento Salgado Filho (POA)', 'Estacionamento no Aeroporto Salgado Filho em Porto Alegre. Tarifas, reservas e facilidades.',
   E'# Guia Master: Estacionamento Salgado Filho (POA)\n\n## Sobre o Aeroporto\n\nO Aeroporto Salgado Filho é o principal aeroporto do Rio Grande do Sul, conectando a região sul ao Brasil.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 32-48 | R$ 7-11 | Estacionamento descoberto |\n| Valet | R$ 52-72 | R$ 11-16 | Serviço de manobrista |\n| Coberto | R$ 42-62 | R$ 9-13 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Como faço a reserva?**\nR: Na Movepark, selecionando tipo e datas desejadas.\n\n**P: Qual é a melhor opção?**\nR: Depende da sua necessidade; valet é conveniente, self-park é econômico.\n\n**P: Há desconto para longa permanência?**\nR: Sim, pacotes especiais para estadias longas.\n\n**P: O inverno afeta o estacionamento?**\nR: Recomendamos coberto no inverno rigoroso.\n\n**P: Qual é a distância do terminal?**\nR: A poucos minutos de caminhada.\n\n**P: Há garantia de devolução rápida?**\nR: Sim, se avisado com antecedência.\n\n**P: O estacionamento fica aberto 24h?**\nR: Sim, vigilância constante.\n\n**P: Posso deixar por um mês?**\nR: Sim, com tarifa especial.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva online\n- [ ] Confirmar horário\n- [ ] Verificar combustível\n- [ ] Inspecionar carro\n- [ ] Fotografar estado\n- [ ] Guardar voucher\n- [ ] Deixar contato\n- [ ] Anotar vaga\n',
   'https://images.movepark.co/blog/guia-master-salgado-filho.jpg', '1e8b522c-31b1-4165-ad71-59bb86706325', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-centro-nova-iguacu', 'Guia Master: Estacionamento Centro de Nova Iguaçu', 'Estacionamento no Centro de Nova Iguaçu. Tarifas, reservas e facilidades para viajantes.',
   E'# Guia Master: Estacionamento Centro de Nova Iguaçu\n\n## Sobre a Localização\n\nNova Iguaçu é uma cidade importante da Baixada Fluminense, com centro comercial e de negócios relevante.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 20-32 | R$ 4-6 | Estacionamento descoberto |\n| Valet | R$ 40-60 | R$ 8-11 | Serviço de manobrista |\n| Coberto | R$ 30-50 | R$ 6-9 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Como funciona a reserva no Centro?**\nR: Na Movepark, selecionando o tipo e datas de permanência.\n\n**P: Qual é a tarifa mais econômica?**\nR: Self-park descoberto a partir de R$ 20 por dia.\n\n**P: Há desconto para negócios?**\nR: Sim, oferecemos pacotes corporativos.\n\n**P: O centro fica próximo ao metrô?**\nR: Sim, com fácil acesso ao transporte público.\n\n**P: Há limite de permanência?**\nR: Não, você pode deixar por quanto tempo quiser.\n\n**P: O estacionamento é seguro?**\nR: Sim, vigilância 24h com câmeras.\n\n**P: Posso cancelar minha reserva?**\nR: Sim, até 48h antes para reembolso.\n\n**P: Há atendimento em inglês?**\nR: Nosso atendimento principal é em português.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva online\n- [ ] Confirmar endereço\n- [ ] Levar documentos\n- [ ] Inspecionar veículo\n- [ ] Fotografar estado\n- [ ] Guardar recibo\n- [ ] Deixar contato\n- [ ] Revisar termos\n',
   'https://images.movepark.co/blog/guia-master-nova-iguacu.jpg', 'e87f47d2-36f1-477a-aed4-360f80d2197c', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-centro-sao-paulo', 'Guia Master: Estacionamento Centro de São Paulo', 'Estacionamento no Centro de São Paulo. Tarifas, reservas e facilidades para negócios.',
   E'# Guia Master: Estacionamento Centro de São Paulo\n\n## Sobre a Localização\n\nO Centro de São Paulo é o coração da capital, com concentração de bancos, comércio e serviços.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 30-45 | R$ 7-10 | Estacionamento coberto |\n| Valet | R$ 50-70 | R$ 10-15 | Serviço de manobrista |\n| Premium | R$ 60-80 | R$ 12-18 | Segurança reforçada |\n\n## Perguntas Frequentes\n\n**P: Como funciona o estacionamento no Centro?**\nR: Na Movepark, você reserva e recebe um código de acesso.\n\n**P: Qual é a opção mais barata?**\nR: Self-park coberto a partir de R$ 30 por dia.\n\n**P: Há vagas para deficientes?**\nR: Sim, com gratuidade ao apresentar cartão de PcD.\n\n**P: O estacionamento fica perto do metrô?**\nR: Sim, com acesso fácil a estações próximas.\n\n**P: Há desconto para funcionários?**\nR: Sim, oferecemos pacotes corporativos.\n\n**P: Posso deixar por 30 dias?**\nR: Sim, com tarifa especial de longa permanência.\n\n**P: Como é a segurança?**\nR: Vigilância 24h, câmeras, alarmes e seguro completo.\n\n**P: Qual é a melhor hora para chegar?**\nR: Madrugada é menos congestionada.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva online\n- [ ] Confirmar dados pessoais\n- [ ] Chegar com tempo\n- [ ] Inspecionar carro\n- [ ] Documentar fotos\n- [ ] Guardar voucher\n- [ ] Deixar telefone\n- [ ] Revisar contrato\n',
   'https://images.movepark.co/blog/guia-master-centro-sp.jpg', 'd7bc75c4-9960-49df-a092-a31f79ff0751', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-jardim-paulista', 'Guia Master: Estacionamento Jardim Paulista', 'Estacionamento no Jardim Paulista em São Paulo. Tarifas, reservas e facilidades residenciais.',
   E'# Guia Master: Estacionamento Jardim Paulista\n\n## Sobre a Localização\n\nJardim Paulista é um bairro nobre de São Paulo, conhecido por residências de alto padrão e comércio sofisticado.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 35-50 | R$ 8-12 | Estacionamento coberto |\n| Valet | R$ 55-75 | R$ 12-18 | Serviço de manobrista |\n| Premium | R$ 65-85 | R$ 14-20 | Segurança reforçada |\n\n## Perguntas Frequentes\n\n**P: Como funciona a reserva?**\nR: Na Movepark, selecionando tipo e datas desejadas.\n\n**P: Qual é a tarifa mais barata?**\nR: Self-park coberto a partir de R$ 35 por dia.\n\n**P: O bairro é seguro?**\nR: Sim, Jardim Paulista é um dos bairros mais seguros de São Paulo.\n\n**P: Há transporte público perto?**\nR: Sim, várias linhas de ônibus e metrô próximos.\n\n**P: Posso deixar o carro por 2 meses?**\nR: Sim, com tarifa especial de longa permanência.\n\n**P: Há vagas para carro de luxo?**\nR: Sim, com seguro especial para veículos de alto valor.\n\n**P: Qual é a segurança?**\nR: Vigilância premium com monitoramento constante.\n\n**P: Como é o atendimento?**\nR: Equipe qualificada disponível 24h.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva antecipada\n- [ ] Confirmar dados\n- [ ] Levar documentação\n- [ ] Inspecionar veículo\n- [ ] Fotografar estado\n- [ ] Guardar voucher\n- [ ] Deixar contato\n- [ ] Revisar termos\n',
   'https://images.movepark.co/blog/guia-master-jardim-paulista.jpg', '9c6b2537-f712-4320-9143-ebae0a7a5c76', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-terminal-tiete', 'Guia Master: Estacionamento Terminal Tietê', 'Estacionamento no Terminal Rodoviário Tietê em São Paulo. Tarifas, reservas e facilidades.',
   E'# Guia Master: Estacionamento Terminal Tietê\n\n## Sobre a Localização\n\nO Terminal Rodoviário Tietê é o maior terminal de ônibus urbano do Brasil, localizado no norte de São Paulo.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | R$ 25-38 | R$ 6-8 | Estacionamento coberto |\n| Valet | R$ 45-65 | R$ 9-13 | Serviço de manobrista |\n| Coberto | R$ 35-55 | R$ 7-10 | Proteção e vigilância |\n\n## Perguntas Frequentes\n\n**P: Como funciona a reserva?**\nR: Na Movepark, selecionando o tipo e datas desejadas.\n\n**P: Qual é a tarifa mais barata?**\nR: Self-park coberto a partir de R$ 25 por dia.\n\n**P: O terminal fica próximo ao metrô?**\nR: Sim, com acesso direto à estação Tietê.\n\n**P: Há ônibus de longa distância?**\nR: Sim, centenas de linhas operando no terminal.\n\n**P: Posso deixar o carro por uma semana?**\nR: Sim, com tarifas especiais.\n\n**P: O estacionamento é seguro?**\nR: Sim, vigilância 24h e seguros disponíveis.\n\n**P: Há vagas para deficientes?**\nR: Sim, com gratuidade ao apresentar cartão de PcD.\n\n**P: Qual é o horário de funcionamento?**\nR: 24 horas, 7 dias por semana.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva com antecedência\n- [ ] Confirmar dados pessoais\n- [ ] Levar carteira de motorista\n- [ ] Inspecionar o veículo\n- [ ] Fotografar documentação\n- [ ] Guardar voucher\n- [ ] Deixar telefone de contato\n- [ ] Anotar número da vaga\n',
   'https://images.movepark.co/blog/guia-master-terminal-tiete.jpg', '63dadc64-a3ba-4e87-8d70-1f3f9b06df8e', true, now(), now(), now()),

  (gen_random_uuid(), 'guia-master-aeroporto-lisboa', 'Guia Master: Estacionamento Aeroporto de Lisboa', 'Estacionamento no Aeroporto Humberto Delgado em Lisboa. Tarifas, reservas e facilidades.',
   E'# Guia Master: Estacionamento Aeroporto de Lisboa\n\n## Sobre o Aeroporto\n\nO Aeroporto Humberto Delgado (Portela) é o principal aeroporto de Lisboa, Portugal, porta de entrada para a Europa.\n\n## Tarifas de Estacionamento\n\n| Tipo | Diária | Por Hora | Observações |\n|------|--------|----------|-------------|\n| Self-Park | EUR 15-25 | EUR 3-5 | Estacionamento descoberto |\n| Valet | EUR 25-35 | EUR 5-8 | Serviço de manobrista |\n| Coberto | EUR 20-30 | EUR 4-6 | Proteção contra intempéries |\n\n## Perguntas Frequentes\n\n**P: Como funciono a reserva em Lisboa?**\nR: Na Movepark, selecionando tipo e datas de permanência.\n\n**P: Qual é a tarifa mais acessível?**\nR: Self-park descoberto a partir de EUR 15 por dia.\n\n**P: O aeroporto fica longe do centro?**\nR: Aproximadamente 8 km, cerca de 15 minutos de carro.\n\n**P: Há transporte público?**\nR: Sim, ônibus, metro e táxi disponíveis.\n\n**P: Posso deixar o carro por um mês?**\nR: Sim, com tarifa especial para longa permanência.\n\n**P: Como é a segurança?**\nR: Vigilância 24h com câmeras em todas as áreas.\n\n**P: Qual é o atendimento?**\nR: Equipe bilíngue (português e inglês) disponível 24h.\n\n**P: Há vagas acessíveis?**\nR: Sim, conforme legislação portuguesa.\n\n## Checklist de Viagem\n\n- [ ] Fazer reserva antecipada\n- [ ] Confirmar dados pessoais\n- [ ] Levar carteira de motorista internacional\n- [ ] Inspecionar o veículo\n- [ ] Documentar fotos\n- [ ] Guardar voucher\n- [ ] Deixar telefone de contato\n- [ ] Revisar documentação do carro\n',
   'https://images.movepark.co/blog/guia-master-lisboa.jpg', '38cfb07a-b785-4803-97a7-7308163f9756', true, now(), now(), now());

-- Trigger to update updated_at timestamp
UPDATE blog_post SET updated_at = now() WHERE slug LIKE 'guia-master-%' AND updated_at = created_at;
